# Generated by Django 4.2 on 2023-05-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=19),
        ),
    ]
