# Generated by Django 4.2 on 2023-05-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_agent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='agent_id',
        ),
    ]
