# Generated by Django 4.2 on 2023-06-01 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '1234567890' or '11234567890' or '+11234567890'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
