# Generated by Django 4.2 on 2023-04-27 15:07

from django.db import migrations, models
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='zip',
            field=localflavor.us.models.USZipCodeField(default='00000', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('US', 'United States of America')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2),
        ),
    ]
