# Generated by Django 4.2 on 2023-04-27 15:49

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_email_order_zip_alter_order_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zip',
            field=localflavor.us.models.USZipCodeField(default='XXXXX', max_length=10),
        ),
    ]
